"""initial schema

Revision ID: 69b0821954c4
Revises: 
Create Date: 2026-06-27 07:03:38.015128

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '69b0821954c4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('is_local', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_multilingual', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_ymyl', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_domain'), 'sites', ['domain'], unique=True)
    op.create_table('audit_runs',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='runstatus', native_enum=False, length=20), nullable=False),
    sa.Column('trigger', sa.Enum('manual', 'scheduled', name='runtrigger', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_site_id'), 'audit_runs', ['site_id'], unique=False)
    op.create_table('connections',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('search_console', 'ga4', 'google_tag_manager', 'ahrefs', 'screaming_frog', name='connectionsource', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('connected', 'error', 'disconnected', name='connectionstatus', native_enum=False, length=30), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_site_id'), 'connections', ['site_id'], unique=False)
    op.create_table('pages',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_run_id'), 'pages', ['run_id'], unique=False)
    op.create_table('sub_audit_results',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('audit_key', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('weighted_contribution', sa.Float(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_audit_results_audit_key'), 'sub_audit_results', ['audit_key'], unique=False)
    op.create_index(op.f('ix_sub_audit_results_run_id'), 'sub_audit_results', ['run_id'], unique=False)
    op.create_table('queries',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_page_id'), 'queries', ['page_id'], unique=False)
    op.create_index(op.f('ix_queries_run_id'), 'queries', ['run_id'], unique=False)
    op.create_table('findings',
    sa.Column('sub_audit_result_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('check_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('passed', 'warn', 'fail', 'info', name='findingstatus', native_enum=False, length=10), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='severity', native_enum=False, length=10), nullable=False),
    sa.Column('detection_tag', sa.Enum('observed', 'inferred', 'needs_connection', name='detectiontag', native_enum=False, length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('query_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sub_audit_result_id'], ['sub_audit_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_check_key'), 'findings', ['check_key'], unique=False)
    op.create_index(op.f('ix_findings_sub_audit_result_id'), 'findings', ['sub_audit_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_sub_audit_result_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_check_key'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_queries_run_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_page_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_sub_audit_results_run_id'), table_name='sub_audit_results')
    op.drop_index(op.f('ix_sub_audit_results_audit_key'), table_name='sub_audit_results')
    op.drop_table('sub_audit_results')
    op.drop_index(op.f('ix_pages_run_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_connections_site_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_audit_runs_site_id'), table_name='audit_runs')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_sites_domain'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
