"""add run email_requested and error_message

Revision ID: cf562560a605
Revises: f26e709cb21e
Create Date: 2026-06-28 10:42:34.345014

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cf562560a605'
down_revision: str | None = 'f26e709cb21e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_runs', sa.Column('email_requested', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('audit_runs', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_runs', 'error_message')
    op.drop_column('audit_runs', 'email_requested')
    # ### end Alembic commands ###
