"""add page depth and status_code

Revision ID: f26e709cb21e
Revises: 69b0821954c4
Create Date: 2026-06-27 22:50:52.991604

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f26e709cb21e'
down_revision: str | None = '69b0821954c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('depth', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('status_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'status_code')
    op.drop_column('pages', 'depth')
    # ### end Alembic commands ###
